spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password: sa
    driver-class-name: org.h2.Driver

# JPA 설정
  jpa:
    hibernate:
      ddl-auto: create # JPA 로딩 시점에, 테이블을 모두 Drop 한 후, 재생성, 애플리케이션 다운 후에도 테이블을 남겨둔다.
  properties:
    hibernate:
      #show_sql: true # JPA 실행 쿼리를 sout으로 콘솔에 찍는다.
      format_sql: true

logging.level:
  org.hibernate.SQL: debug # JPA 실행 쿼리를 로그 파일에 남긴다.
#  org.hibernate.type: trace